apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: canary-cluster
  region: us-east-1
  version: "1.21"

availabilityZones: 
  - us-east-1a
  - us-east-1b
  - us-east-1c
fargateProfiles:
  - name: fp-all
    selectors:
      - namespace: kube-system
      - namespace: istio-system

managedNodeGroups:
  - name: managed-ng-1
    instanceType: t3a.medium
    minSize: 1
    maxSize: 4
    desiredCapacity: 4
    volumeSize: 20