#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

export DIR="${PWD}"

function green() {
    text="${1:- }"
    echo -e "\033[32m${text}\033[0m"
}

function install_dep() {
    green "Installing eksctl"
    curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
    sudo mv /tmp/eksctl /usr/local/bin

    green "Installing kubectl"
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    

    green "Installing istioctl"
    cd ~
    curl -L https://istio.io/downloadIstio | sh -
    export PATH="$PATH:~/istio-1.11.0/bin"
}

green "Installing pre-requisites"
install_dep

cd "${DIR}"
green "Deploying Cluster => canary-cluster"
eksctl create cluster -f canary-cluster.yaml 

green "Cluster => "
kubectl config current-context

green "Setting up Istio"
istioctl install --set profile=default -y

green "Adding Istio label to default namespace"
kubectl label namespace default istio-injection=enabled

green "Deploying Sample application and Kiali CRD"
kubectl apply -f manifests/

green "Deploying Istio addons"
kubectl apply -f https://raw.githubusercontent.com/istio/istio/1.10.3/samples/addons/prometheus.yaml
kubectl apply -f https://raw.githubusercontent.com/istio/istio/1.10.3/samples/addons/grafana.yaml
kubectl apply -f https://raw.githubusercontent.com/istio/istio/1.10.3/samples/addons/kiali.yaml

