#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

function green() {
    text="${1:- }"
    echo -e "\033[32m${text}\033[0m"
}

green "Deploying Cluster => canary-cluster"
eksctl create cluster -f canary-cluster.yaml 

green "Setting up Istio"
istioctl install --set profile=default -y

green "Cluster => "
kubectl config current-context

green "Adding Istio label to default namespace"
kubectl label namespace default istio-injection=enabled

green "Deploying sample application"
kubectl apply -f manifests/

